const users = [
    {
      username: "valts",
      email: "valts.p@ggg.gb",
      isAdmin: true,
      passwordHash: "$2b$10$xiosBQB4Wf60ZY2lbWMw5.Sg1pQ/1sVs6kEkW/k.KPdxKXOzpkvIu"
    },
    {
      username: "john_doe",
      email: "john_doe@gmail.com",
      passwordHash: "$2b$10$nOUIs5kJ7naTuTFkBy1veuK0kSxUFXfuaOKdOKf9xYT0KKIGSJwFa"
    },
    {
      username: "jane_smith",
      email: "jjanes@yh.com",
      passwordHash: "$2b$10$nOUIs5kJ7naTuTFkBy1veuK0kSxUFXfuaOKdOKf9xYT0KKIGSJwFa"
    }
]
  
const workouts = [
    {
      title: "Morning Push Day",
      durationMinutes: 60,
      difficulty: "medium",
      exerciseIds: [1, 2],
      notes: "Felt strong, increased weight on squats.",
      userId: 1
    },
    {
      title: "Leg Day",
      durationMinutes: 75,
      difficulty: "hard",
      exerciseIds: [1, 4],
      notes: "Box jumps after squats was brutal.",
      userId: 1
    },
    {
      title: "Active Recovery",
      durationMinutes: 30,
      difficulty: "easy",
      exerciseIds: [3],
      notes: "Easy tempo run, kept HR below 150.",
      userId: 2
    },
    {
      title: "Full Body Strength",
      durationMinutes: 90,
      difficulty: "hard",
      exerciseIds: [1, 2, 4],
      notes: "",
      userId: 3
    }
  ]

  const exercises = [
    {
        name: "Barbell Back Squat",
        category: "strength",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["hamstrings", "core"] },
        movementPattern: "squat",
        equipment: ["barbell", "squat rack"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 5, max: 8 },
        restSeconds: 180,
        instructions: "Brace core, descend until thighs are parallel, drive through heels.",
        tips: "Keep chest up and knees tracking over toes.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Romanian Deadlift",
        category: "strength",
        muscleGroups: { primary: ["hamstrings", "glutes"], secondary: ["lower back"] },
        movementPattern: "hinge",
        equipment: ["barbell"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 6, max: 10 },
        restSeconds: 120,
        instructions: "Hinge at the hips, lower bar along shins, feel a stretch in the hamstrings.",
        tips: "Keep the bar close to your legs the entire movement.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Barbell Bench Press",
        category: "strength",
        muscleGroups: { primary: ["chest", "triceps"], secondary: ["shoulders"] },
        movementPattern: "push",
        equipment: ["barbell", "bench"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 6, max: 10 },
        restSeconds: 150,
        instructions: "Lower bar to mid-chest with control, press up to lockout.",
        tips: "Keep shoulder blades pinned and feet planted.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Overhead Press",
        category: "strength",
        muscleGroups: { primary: ["shoulders", "triceps"], secondary: ["core"] },
        movementPattern: "push",
        equipment: ["barbell"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 5, max: 8 },
        restSeconds: 150,
        instructions: "Press bar overhead in a straight line, finishing with biceps by ears.",
        tips: "Squeeze glutes to avoid over-arching the lower back.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Weighted Pull-Up",
        category: "strength",
        muscleGroups: { primary: ["lats", "biceps"], secondary: ["forearms"] },
        movementPattern: "pull",
        equipment: ["pull-up bar", "weight belt"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 4, max: 6 },
        restSeconds: 150,
        instructions: "Pull chin over the bar, control the descent to a full hang.",
        tips: "Drive elbows down and back rather than just curling up.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Barbell Row",
        category: "strength",
        muscleGroups: { primary: ["lats", "rhomboids"], secondary: ["biceps", "rear delts"] },
        movementPattern: "pull",
        equipment: ["barbell"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 6, max: 10 },
        restSeconds: 120,
        instructions: "Hinge to roughly 45 degrees, row bar to lower ribs.",
        tips: "Avoid using momentum from the lower back.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Bulgarian Split Squat",
        category: "strength",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["hamstrings"] },
        movementPattern: "lunge",
        equipment: ["dumbbells", "bench"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 8, max: 12 },
        restSeconds: 90,
        instructions: "Rear foot elevated, lower until front thigh is parallel to floor.",
        tips: "Keep most of your weight on the front heel.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Walking Lunge",
        category: "strength",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["hamstrings", "core"] },
        movementPattern: "lunge",
        equipment: ["dumbbells"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 10, max: 14 },
        restSeconds: 90,
        instructions: "Step forward into a lunge, drive through the front heel to stand and step through.",
        tips: "Keep torso tall and avoid letting the front knee cave in.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Dumbbell Shoulder Press",
        category: "strength",
        muscleGroups: { primary: ["shoulders"], secondary: ["triceps"] },
        movementPattern: "push",
        equipment: ["dumbbells", "bench"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 8, max: 12 },
        restSeconds: 90,
        instructions: "Press dumbbells overhead until arms are extended, without locking elbows hard.",
        tips: "Keep ribcage down to protect the lower back.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Barbell Hip Thrust",
        category: "strength",
        muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
        movementPattern: "hinge",
        equipment: ["barbell", "bench"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 8, max: 12 },
        restSeconds: 120,
        instructions: "Drive hips upward until torso is parallel with a full glute squeeze at the top.",
        tips: "Keep chin tucked and ribs down through the movement.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Dumbbell Bicep Curl",
        category: "strength",
        muscleGroups: { primary: ["biceps"], secondary: ["forearms"] },
        movementPattern: "pull",
        equipment: ["dumbbells"],
        mechanics: "isolation",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 10, max: 15 },
        restSeconds: 60,
        instructions: "Curl dumbbells up while keeping elbows pinned to the sides.",
        tips: "Avoid swinging the torso to generate momentum.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Goblet Squat",
        category: "strength",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["core"] },
        movementPattern: "squat",
        equipment: ["dumbbell", "kettlebell"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 10, max: 15 },
        restSeconds: 75,
        instructions: "Hold weight at chest, squat down keeping elbows inside the knees.",
        tips: "Drive knees out in line with the toes.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Kettlebell Swing",
        category: "strength",
        muscleGroups: { primary: ["glutes", "hamstrings"], secondary: ["core", "shoulders"] },
        movementPattern: "hinge",
        equipment: ["kettlebell"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 12, max: 20 },
        restSeconds: 90,
        instructions: "Hinge and hike the bell back, snap hips forward to drive it to chest height.",
        tips: "Power comes from the hips, not the arms or shoulders.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Kettlebell Goblet Lunge",
        category: "strength",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["core"] },
        movementPattern: "lunge",
        equipment: ["kettlebell"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 8, max: 12 },
        restSeconds: 75,
        instructions: "Hold kettlebell at chest, step into a lunge keeping torso upright.",
        tips: "Keep the front knee tracking over the foot.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Single Arm Kettlebell Row",
        category: "strength",
        muscleGroups: { primary: ["lats", "rhomboids"], secondary: ["biceps"] },
        movementPattern: "pull",
        equipment: ["kettlebell", "bench"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 8, max: 12 },
        restSeconds: 75,
        instructions: "Support on bench with one arm, row kettlebell to the hip.",
        tips: "Avoid rotating the torso as you pull.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Kettlebell Turkish Get-Up",
        category: "strength",
        muscleGroups: { primary: ["shoulders", "core"], secondary: ["glutes"] },
        movementPattern: "carry",
        equipment: ["kettlebell"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 3, max: 5 },
        restSeconds: 90,
        instructions: "Move from lying to standing while keeping the kettlebell locked out overhead.",
        tips: "Move slowly and keep your eyes on the bell throughout.",
        userId: 2,
        videoUrl: "https://example.com/turkish-get-up"
    },
    {
        name: "Farmer's Carry",
        category: "strength",
        muscleGroups: { primary: ["forearms", "traps"], secondary: ["core"] },
        movementPattern: "carry",
        equipment: ["kettlebells"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 1, max: 1 },
        restSeconds: 90,
        instructions: "Walk a set distance holding heavy weights at the sides with a tall posture.",
        tips: "Keep shoulders packed down and avoid leaning side to side.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Dead Hang",
        category: "isometric strength",
        muscleGroups: { primary: ["lats", "forearms"], secondary: null },
        movementPattern: "carry",
        equipment: ["pull-up bar"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 20, maxSeconds: 60 },
        restSeconds: 90,
        instructions: "Hang from bar with arms fully extended and shoulders packed.",
        tips: "Avoid shrugging — actively depress the scapulae.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Plank",
        category: "isometric strength",
        muscleGroups: { primary: ["core"], secondary: ["shoulders"] },
        movementPattern: "brace",
        equipment: [],
        mechanics: "isolation",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 30, maxSeconds: 90 },
        restSeconds: 60,
        instructions: "Hold a straight line from head to heels, bracing the core.",
        tips: "Squeeze glutes to prevent the hips from sagging.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Side Plank",
        category: "isometric strength",
        muscleGroups: { primary: ["obliques"], secondary: ["shoulders"] },
        movementPattern: "brace",
        equipment: [],
        mechanics: "isolation",
        laterality: "unilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 20, maxSeconds: 45 },
        restSeconds: 60,
        instructions: "Stack feet and hips, lift into a straight line supported on one forearm.",
        tips: "Keep hips high and avoid rotating forward.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Wall Sit",
        category: "isometric strength",
        muscleGroups: { primary: ["quads"], secondary: ["glutes"] },
        movementPattern: "squat",
        equipment: ["wall"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 30, maxSeconds: 60 },
        restSeconds: 90,
        instructions: "Slide down the wall until thighs are parallel and hold the position.",
        tips: "Keep knees tracking directly over the ankles.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Kettlebell Rack Hold",
        category: "isometric strength",
        muscleGroups: { primary: ["core", "shoulders"], secondary: ["forearms"] },
        movementPattern: "carry",
        equipment: ["kettlebell"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 20, maxSeconds: 40 },
        restSeconds: 75,
        instructions: "Hold kettlebell in the rack position while maintaining a tall, braced torso.",
        tips: "Keep the wrist neutral and elbow tucked close to the ribs.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Hollow Body Hold",
        category: "isometric strength",
        muscleGroups: { primary: ["core"], secondary: null },
        movementPattern: "brace",
        equipment: [],
        mechanics: "isolation",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 15, maxSeconds: 40 },
        restSeconds: 60,
        instructions: "Lie on back, press lower back into the floor, lift shoulders and legs.",
        tips: "Keep the lower back glued to the floor throughout.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Overhead Kettlebell Hold",
        category: "isometric strength",
        muscleGroups: { primary: ["shoulders", "core"], secondary: null },
        movementPattern: "carry",
        equipment: ["kettlebell"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 15, maxSeconds: 30 },
        restSeconds: 75,
        instructions: "Press kettlebell overhead and hold with a locked-out, stacked arm.",
        tips: "Avoid letting the ribcage flare or the shoulder shrug up.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Glute Bridge Hold",
        category: "isometric strength",
        muscleGroups: { primary: ["glutes"], secondary: ["hamstrings"] },
        movementPattern: "hinge",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 20, maxSeconds: 45 },
        restSeconds: 60,
        instructions: "Lift hips to full extension and hold with a firm glute squeeze.",
        tips: "Avoid overextending through the lower back.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "L-Sit",
        category: "isometric strength",
        muscleGroups: { primary: ["core", "hip flexors"], secondary: ["triceps"] },
        movementPattern: "brace",
        equipment: ["parallettes"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 10, maxSeconds: 30 },
        restSeconds: 90,
        instructions: "Support body on hands with legs extended straight in front, hips off the ground.",
        tips: "Push down through the shoulders and keep the legs together.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Bear Hold",
        category: "isometric strength",
        muscleGroups: { primary: ["core"], secondary: ["shoulders"] },
        movementPattern: "brace",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        durationRange: { minSeconds: 20, maxSeconds: 40 },
        restSeconds: 60,
        instructions: "Hover knees an inch off the floor on hands and toes, keeping the back flat.",
        tips: "Keep hips level with the shoulders, don't pike up.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Tempo Run",
        category: "cardio",
        muscleGroups: { primary: ["quads", "calves"], secondary: ["glutes", "hamstrings"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 1,
        durationRange: { minMinutes: 20, maxMinutes: 40 },
        targetPaceMinPerKm: { min: 4, max: 5 },
        restSeconds: 0,
        instructions: "Run at a comfortably hard effort — roughly 7/10 perceived exertion.",
        tips: "Aim for a cadence around 170-180 spm and keep breathing controlled.",
        userId: 1,
        videoUrl: "https://example.com/tempo-run"
    },
    {
        name: "Easy Recovery Run",
        category: "cardio",
        muscleGroups: { primary: ["quads", "calves"], secondary: ["glutes"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 1,
        durationRange: { minMinutes: 25, maxMinutes: 45 },
        targetPaceMinPerKm: { min: 6, max: 7 },
        restSeconds: 0,
        instructions: "Jog at a conversational pace focused purely on recovery.",
        tips: "If you can't hold a conversation, slow down further.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Long Run",
        category: "cardio",
        muscleGroups: { primary: ["quads", "calves"], secondary: ["glutes", "hamstrings"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 1,
        durationRange: { minMinutes: 60, maxMinutes: 90 },
        targetPaceMinPerKm: { min: 5, max: 6 },
        restSeconds: 0,
        instructions: "Sustain an easy, steady pace for the full duration to build aerobic base.",
        tips: "Fuel and hydrate ahead of time for runs over an hour.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Interval Sprints",
        category: "cardio",
        muscleGroups: { primary: ["quads", "hamstrings"], secondary: ["calves", "glutes"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 8,
        durationRange: { minMinutes: 1, maxMinutes: 2 },
        targetPaceMinPerKm: { min: 3, max: 4 },
        restSeconds: 90,
        instructions: "Sprint at near-maximal effort for the interval, then walk to recover.",
        tips: "Warm up thoroughly before the first hard interval.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Hill Repeats",
        category: "cardio",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 6,
        durationRange: { minMinutes: 1, maxMinutes: 2 },
        targetPaceMinPerKm: { min: 4, max: 5 },
        restSeconds: 120,
        instructions: "Run hard up a moderate incline, jog back down for recovery.",
        tips: "Drive the knees and lean slightly into the hill.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Stationary Bike Intervals",
        category: "cardio",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves"] },
        movementPattern: "locomotion",
        equipment: ["stationary bike"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 10,
        durationRange: { minMinutes: 1, maxMinutes: 1 },
        restSeconds: 60,
        instructions: "Alternate hard efforts with easy spinning at a set cadence.",
        tips: "Keep cadence high rather than grinding a heavy gear.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Rowing Erg Intervals",
        category: "cardio",
        muscleGroups: { primary: ["lats", "quads"], secondary: ["core", "hamstrings"] },
        movementPattern: "pull",
        equipment: ["rowing machine"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 6,
        durationRange: { minMinutes: 2, maxMinutes: 3 },
        restSeconds: 90,
        instructions: "Drive legs first, then hinge and pull the handle to the ribs.",
        tips: "Keep the stroke rate controlled rather than rushing the recovery.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Jump Rope Conditioning",
        category: "cardio",
        muscleGroups: { primary: ["calves"], secondary: ["shoulders", "core"] },
        movementPattern: "jump",
        equipment: ["jump rope"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 5,
        durationRange: { minMinutes: 2, maxMinutes: 3 },
        restSeconds: 60,
        instructions: "Jump with small, quick hops, keeping elbows close to the body.",
        tips: "Land softly on the balls of the feet.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Stair Climbing",
        category: "cardio",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves"] },
        movementPattern: "locomotion",
        equipment: ["stairs"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 1,
        durationRange: { minMinutes: 15, maxMinutes: 30 },
        restSeconds: 0,
        instructions: "Climb at a steady, sustainable pace using the full foot on each step.",
        tips: "Use the handrail sparingly to keep the legs doing the work.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Swimming Intervals",
        category: "cardio",
        muscleGroups: { primary: ["lats", "shoulders"], secondary: ["core", "triceps"] },
        movementPattern: "pull",
        equipment: ["pool"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 8,
        durationRange: { minMinutes: 1, maxMinutes: 2 },
        restSeconds: 45,
        instructions: "Swim at a strong, controlled effort focusing on stroke technique.",
        tips: "Keep hips high in the water to reduce drag.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Fartlek Run",
        category: "cardio",
        muscleGroups: { primary: ["quads", "calves"], secondary: ["glutes"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 1,
        durationRange: { minMinutes: 30, maxMinutes: 45 },
        targetPaceMinPerKm: { min: 4, max: 6 },
        restSeconds: 0,
        instructions: "Vary pace freely between hard surges and easy jogging throughout the run.",
        tips: "Use landmarks like lampposts to mark surge segments.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Box Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves", "core"] },
        movementPattern: "jump",
        equipment: ["plyo box"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 5, max: 8 },
        restSeconds: 120,
        instructions: "Hinge into a quarter squat, explode upward, land softly with bent knees.",
        tips: "Reset fully between reps — this is a power exercise, not a cardio one.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Broad Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["hamstrings", "calves"] },
        movementPattern: "jump",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 4, max: 6 },
        restSeconds: 120,
        instructions: "Swing arms back, then explode forward, landing softly with bent knees.",
        tips: "Stick the landing before resetting for the next rep.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Depth Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves"] },
        movementPattern: "jump",
        equipment: ["plyo box"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 4, max: 6 },
        restSeconds: 150,
        instructions: "Step off the box, land softly, then immediately explode into a vertical jump.",
        tips: "Minimize ground contact time on the landing.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Lateral Bound",
        category: "plyometrics",
        muscleGroups: { primary: ["glutes", "quads"], secondary: ["hip abductors"] },
        movementPattern: "jump",
        equipment: [],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 6, max: 10 },
        restSeconds: 90,
        instructions: "Push off one leg sideways, land softly on the opposite leg, and stabilize.",
        tips: "Control the landing before bounding back the other way.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Tuck Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["quads", "core"], secondary: ["calves", "hip flexors"] },
        movementPattern: "jump",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 6, max: 10 },
        restSeconds: 90,
        instructions: "Jump vertically, driving both knees up toward the chest.",
        tips: "Land soft and quiet to minimize joint stress.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Plyo Push-Up",
        category: "plyometrics",
        muscleGroups: { primary: ["chest", "triceps"], secondary: ["shoulders", "core"] },
        movementPattern: "push",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 5, max: 8 },
        restSeconds: 90,
        instructions: "Lower to the floor, then push explosively so hands leave the ground.",
        tips: "Absorb the landing with soft elbows.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Skater Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["glutes", "quads"], secondary: ["hip abductors", "calves"] },
        movementPattern: "jump",
        equipment: [],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 8, max: 12 },
        restSeconds: 75,
        instructions: "Leap laterally from one leg to the other in a skating motion.",
        tips: "Keep the chest up and avoid collapsing the landing knee inward.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Medicine Ball Slam",
        category: "plyometrics",
        muscleGroups: { primary: ["core", "shoulders"], secondary: ["lats"] },
        movementPattern: "throw",
        equipment: ["medicine ball"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 8, max: 12 },
        restSeconds: 75,
        instructions: "Raise ball overhead, then slam it forcefully into the ground.",
        tips: "Hinge at the hips to add power rather than rounding the back.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Kettlebell Swing Jump Combo",
        category: "plyometrics",
        muscleGroups: { primary: ["glutes", "hamstrings"], secondary: ["core", "calves"] },
        movementPattern: "hinge",
        equipment: ["kettlebell", "plyo box"],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 3,
        repRange: { min: 6, max: 10 },
        restSeconds: 120,
        instructions: "Perform a kettlebell swing then immediately follow with a box jump.",
        tips: "Prioritize crisp hip snap on the swing before transitioning to the jump.",
        userId: 3,
        videoUrl: null
    },
    {
        name: "Single Leg Box Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves", "hip stabilizers"] },
        movementPattern: "jump",
        equipment: ["plyo box"],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 3,
        repRange: { min: 4, max: 6 },
        restSeconds: 120,
        instructions: "Push off one leg onto the box, landing with control on the same leg.",
        tips: "Start with a low box and progress height gradually.",
        userId: 1,
        videoUrl: null
    },
    {
        name: "Bounding",
        category: "plyometrics",
        muscleGroups: { primary: ["hamstrings", "glutes"], secondary: ["quads", "calves"] },
        movementPattern: "locomotion",
        equipment: [],
        mechanics: "compound",
        laterality: "unilateral",
        defaultSets: 4,
        repRange: { min: 10, max: 10 },
        restSeconds: 90,
        instructions: "Take exaggerated running strides, emphasizing height and distance per stride.",
        tips: "Drive the opposite arm forward to help project the body.",
        userId: 2,
        videoUrl: null
    },
    {
        name: "Squat Jump",
        category: "plyometrics",
        muscleGroups: { primary: ["quads", "glutes"], secondary: ["calves"] },
        movementPattern: "squat",
        equipment: [],
        mechanics: "compound",
        laterality: "bilateral",
        defaultSets: 4,
        repRange: { min: 8, max: 12 },
        restSeconds: 90,
        instructions: "Squat down and explode upward into a jump, landing softly.",
        tips: "Absorb the landing quietly through the whole foot.",
        userId: 3,
        videoUrl: null
    }
]

export default {
    users,
    workouts,
    exercises
}